
export const KIOSK_STRINGS = {
    welcome: "Welcome",
    kfTea: "Kung Fu Tea",
    orders: "Orders",
    signOut: "Sign Out",
    menu: "Menu",
    loading: "Loading...",
    tAgain: "Try Again",
    add: "+ Add",
    yourOrder: "Your Order",
    emptyOrder: "Your cart is empty",
    instructions: "Tap items to add them",
    subtotal: "Subtotal",
    tax: "Tax",
    total: "Total",
    cancel: "Cancel",
    pay: "Pay",
    payQ: "How would you like to pay?",
};